// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Resto.Front.Api.Sagi.DataAccess.Contexts;

namespace Resto.Front.Api.Sagi.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220130181716_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Resto.Front.Api.Sagi.Entities.ConfigurationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configurations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "123456",
                            PhoneNumber = "+77083154319",
                            WebAddress = "https://test.sagi.kz"
                        });
                });

            modelBuilder.Entity("Resto.Front.Api.Sagi.Entities.OrderTransactionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AddStamp")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GiveAward")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IikoOrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<long>("SagiOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionDetail")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WriteOffSum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StampCount")
                       .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OrderTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
