//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resto.Front.Api.Sagi.Plugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resto.Front.Api.Sagi.Plugin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagi.
        /// </summary>
        internal static string SystemKey {
            get {
                return ResourceManager.GetString("SystemKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagi.
        /// </summary>
        internal static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начисление бонуса.
        /// </summary>
        internal static string TitleAccrualBonuses {
            get {
                return ResourceManager.GetString("TitleAccrualBonuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиенту будет начислено {0} бонусов ({1}% от суммы чека). Начислить бонусы?.
        /// </summary>
        internal static string TitleAccrualBonusesInfoMessage {
            get {
                return ResourceManager.GetString("TitleAccrualBonusesInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начисление бонусов Sagi прошло успешно!.
        /// </summary>
        internal static string TitleAccrualBonusesSucceeded {
            get {
                return ResourceManager.GetString("TitleAccrualBonusesSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдача штампиков.
        /// </summary>
        internal static string TitleAddStamp {
            get {
                return ResourceManager.GetString("TitleAddStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У клиента {0} из {1} штампиков. Выдать штампик клиенту?.
        /// </summary>
        internal static string TitleAddStampInfoMessage {
            get {
                return ResourceManager.GetString("TitleAddStampInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма к оплате.
        /// </summary>
        internal static string TitleAmountToPay {
            get {
                return ResourceManager.GetString("TitleAmountToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена транзакции в Sagi. Пожалуйста подождите....
        /// </summary>
        internal static string TitleCancelTransactionPleaseWaiting {
            get {
                return ResourceManager.GetString("TitleCancelTransactionPleaseWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить данные Sagi по идентификатору заказа.
        /// </summary>
        internal static string TitleCannotGetUserDataByOrderId {
            get {
                return ResourceManager.GetString("TitleCannotGetUserDataByOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите 6-значный код клиента.
        /// </summary>
        internal static string TitleCodeInput {
            get {
                return ResourceManager.GetString("TitleCodeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не был передан номер телефона или 6-значный код.
        /// </summary>
        internal static string TitleCodeOrNumberWasNotEntered {
            get {
                return ResourceManager.GetString("TitleCodeOrNumberWasNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент найден. Доступно бонусов: {0}. Количество штампиков {1} из {2}.
        /// </summary>
        internal static string TitleCustomerFound {
            get {
                return ResourceManager.GetString("TitleCustomerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификация клиента Sagi.
        /// </summary>
        internal static string TitleCustomerIdentification {
            get {
                return ResourceManager.GetString("TitleCustomerIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент не найден.
        /// </summary>
        internal static string TitleCustomerNotFound {
            get {
                return ResourceManager.GetString("TitleCustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент отказался от начисление бонуса.
        /// </summary>
        internal static string TitleCustomerRefusedAccrueBonuses {
            get {
                return ResourceManager.GetString("TitleCustomerRefusedAccrueBonuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработка данных Sagi. Пожалуйста, подождите....
        /// </summary>
        internal static string TitleDataProcessingPleaseWaiting {
            get {
                return ResourceManager.GetString("TitleDataProcessingPleaseWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string TitleDate {
            get {
                return ResourceManager.GetString("TitleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдача подарка.
        /// </summary>
        internal static string TitleGiveAward {
            get {
                return ResourceManager.GetString("TitleGiveAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У клиента {0} из {1} штампиков. Выдать подарок клиенту?.
        /// </summary>
        internal static string TitleGiveAwardInfoMessage {
            get {
                return ResourceManager.GetString("TitleGiveAwardInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно бонусов для списания.
        /// </summary>
        internal static string TitleNotEnoughBonusesToWriteOff {
            get {
                return ResourceManager.GetString("TitleNotEnoughBonusesToWriteOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма заказа.
        /// </summary>
        internal static string TitleOrderAmount {
            get {
                return ResourceManager.GetString("TitleOrderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер заказа.
        /// </summary>
        internal static string TitleOrderId {
            get {
                return ResourceManager.GetString("TitleOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор заказа: {0}.
        /// </summary>
        internal static string TitleOrderIdMessage {
            get {
                return ResourceManager.GetString("TitleOrderIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата пустого заказа невозможна!.
        /// </summary>
        internal static string TitlePaymentForEmptyOrderNotPossible {
            get {
                return ResourceManager.GetString("TitlePaymentForEmptyOrderNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер телефона клиента.
        /// </summary>
        internal static string TitlePhoneInput {
            get {
                return ResourceManager.GetString("TitlePhoneInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать Slip чека....
        /// </summary>
        internal static string TitlePrintSlipReceipt {
            get {
                return ResourceManager.GetString("TitlePrintSlipReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagi: настройки.
        /// </summary>
        internal static string TitleSagiSettings {
            get {
                return ResourceManager.GetString("TitleSagiSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка на стороне Sagi {0}.
        /// </summary>
        internal static string TitleSagiSideError {
            get {
                return ResourceManager.GetString("TitleSagiSideError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск клиента Sagi по коду {0}.
        /// </summary>
        internal static string TitleSearchCustomerByCode {
            get {
                return ResourceManager.GetString("TitleSearchCustomerByCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск клиента Sagi по телефону {0}.
        /// </summary>
        internal static string TitleSearchCustomerByPhone {
            get {
                return ResourceManager.GetString("TitleSearchCustomerByPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите количество начисляемых штампиков. (У клиента {0} из {1} штампиков).
        /// </summary>
        internal static string TitleStampCountInfoMessage {
            get {
                return ResourceManager.GetString("TitleStampCountInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество начисляемых штампиков не может быть больше {0}..
        /// </summary>
        internal static string TitleStampFailedMessage {
            get {
                return ResourceManager.GetString("TitleStampFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система.
        /// </summary>
        internal static string TitleSystem {
            get {
                return ResourceManager.GetString("TitleSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные Sagi успешно сохранены. Можно оплачивать заказ!.
        /// </summary>
        internal static string TitleTransactionDataSaved {
            get {
                return ResourceManager.GetString("TitleTransactionDataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID транзакции.
        /// </summary>
        internal static string TitleTransactionId {
            get {
                return ResourceManager.GetString("TitleTransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработка транзакции Sagi. Пожалуйста подождите....
        /// </summary>
        internal static string TitleTransactionProcessingPleaseWaiting {
            get {
                return ResourceManager.GetString("TitleTransactionProcessingPleaseWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь отказался от ввода.
        /// </summary>
        internal static string TitleUserRefusedInput {
            get {
                return ResourceManager.GetString("TitleUserRefusedInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Списано бонусов.
        /// </summary>
        internal static string TitleWriteOffBonuses {
            get {
                return ResourceManager.GetString("TitleWriteOffBonuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите количество бонусов, которое хотите списать. (Доступно {0} бонусов).
        /// </summary>
        internal static string TitleWriteOffBonusesInfoMessage {
            get {
                return ResourceManager.GetString("TitleWriteOffBonusesInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Списание бонусов Sagi прошло успешно!.
        /// </summary>
        internal static string TitleWriteOffBonusesSucceeded {
            get {
                return ResourceManager.GetString("TitleWriteOffBonusesSucceeded", resourceCulture);
            }
        }
    }
}
